### PR TITLE
Runs entirely in client-side Javascript

### PR DESCRIPTION
**Pull request by hufman**
No longer needs PHP on the web server side

### CODE REVIEW

**Comment by hufman** [comment]
Actually I think there's a bug, I'll fix it tomorrow.
What do you think of it otherwise?

**Comment by hufman** [comment]
Ok, fixed the bug that I found. How does it look to you?

**Comment by pommi** [comment]
Amazing work Walter! :tada:

Btw. the last 3 graphs (Block IO Latency, File metadata Latency and File metadata (read) Latency) are broken when I use the sample data from bonnie.csv. Do you have any idea why?

**Comment by hufman** [comment]
I think it's because my parse_csv is lazy and didn't fill out the extra columns if it's parsing old-format lines! I'll fix that up now.

**Comment by hufman** [comment]
Filled in the missing columns from the old style of lines, which fixes those extra graphs.

**Comment by pommi** [comment]
Thanks! Now those work as well.

**Pull request merged**
